Wiki/Controllers/BaseController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

using Wiki.Models.DAL;

namespace Wiki.Controllers
{
    public class BaseController : Controller
    {
        private WikiContext db;

        public BaseController()
        {
            ActualiserTitres();
        }

        public ActionResult ActualiserTitres()
        {
            db = new WikiContext();
            ViewBag.articles = db.Articles.ToList();
            return PartialView();
        }
    }
}

Wiki/Controllers/UtilisateursController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Wiki.Models.Biz;
using Wiki.Models.DAL;
using Wiki.Models.Views;
using System.Web.Security;

namespace Wiki.Controllers
{
    public class UtilisateursController : Controller
    {
        WikiContext db = new WikiContext();
        Utilisateur utilisateurActuel;

        // GET: Utilisateurs
        public ActionResult Index()
        {
            return View();
        }
        
        // GET
        public ActionResult Connexion(string returnUrl = "")
        {
            return View();
        }

        [HttpPost]
        public ActionResult Connexion(UtilisateursConnexionViewModel utilisateurConnexionViewModel, bool connexionPersistante, string returnUrl = "/Home/Index")
        {
            if (ModelState.IsValid)
            {
                if (Utilisateur.EstValide(utilisateurConnexionViewModel.Courriel, utilisateurConnexionViewModel.MDP))
                {
                    FormsAuthentication.SetAuthCookie(utilisateurConnexionViewModel.Courriel, connexionPersistante);

                    utilisateurActuel = Utilisateur.RetourneUtilisateur(utilisateurConnexionViewModel.Courriel);

                    return RedirectToAction("ChangerLangue", "Home", new { langue = utilisateurActuel.Langue, returnUrl = returnUrl });
                }
            }

            return View(utilisateurConnexionViewModel);
        }

        public ActionResult Deconnexion()
        {
            FormsAuthentication.SignOut();

            return RedirectToAction("Index", "Home");
        }

        // GET
        public ActionResult Inscription()
        {
            return View(new UtilisateurInscriptionViewModel());
        }

        [HttpPost]
        public ActionResult Inscription(UtilisateurInscriptionViewModel utilisateurInscriptionViewModel, string returnUrl = "/Home/Index")
        {
            if (ModelState.IsValid)
            {
                utilisateurActuel = Utilisateur.Inscrire(utilisateurInscriptionViewModel);

                FormsAuthentication.SetAuthCookie(utilisateurInscriptionViewModel.Courriel, false);

                return RedirectToAction("ChangerLangue", "Home", new { langue = utilisateurActuel.Langue, returnUrl = returnUrl });
            }

            return View(utilisateurInscriptionViewModel);
        }

        // GET
        public ActionResult Profil()
        {
            UtilisateurProfilViewModel utiliModif = new UtilisateurProfilViewModel(Utilisateur.RetourneUtilisateur(User.Identity.Name));

            return View(utiliModif);
        }

        [HttpPost]
        public ActionResult Profil(UtilisateurProfilViewModel utilisateurProfilViewModel, string returnUrl = "/Home/Index")
        {
            if (ModelState.IsValid)
            {
                utilisateurProfilViewModel.Courriel = User.Identity.Name;

                utilisateurActuel = Utilisateur.ModifierProfil(utilisateurProfilViewModel);

                return RedirectToAction("ChangerLangue", "Home", new { langue = utilisateurActuel.Langue, returnUrl = returnUrl });
            }

            return View(utilisateurProfilViewModel);
        }
        
        // GET
        [Authorize]
        public ActionResult ModifierMDP()
        {
            return View();
        }

        [HttpPost]
        [Authorize]
        public ActionResult ModifierMDP(UtilisateurModifierMDPViewModel utilisateurModifMDPViewModel, string returnUrl = "/Home/Index")
        {
            if (ModelState.IsValid)
            {
                utilisateurModifMDPViewModel.Courriel = User.Identity.Name;

                if (Utilisateur.EstValide(utilisateurModifMDPViewModel.Courriel, utilisateurModifMDPViewModel.AncienMDP))
                {
                    Utilisateur.ModifierMDP(utilisateurModifMDPViewModel);

                    return Redirect(returnUrl);
                }
            }
            return Redirect(returnUrl);
        }
    }
}

Wiki/Views/Shared/Menu.cshtml
@using Wiki.Resources.Shared

@{ 
    //http://stackoverflow.com/questions/3151082/problem-with-asp-net-mvc-selectlist-and-listselectlistitems
    List<SelectListItem> langues = new List<SelectListItem>();
    langues.Add(new SelectListItem() { Text = StringShared.Langues, Selected = true, Value = "" });
    langues.Add(new SelectListItem() { Text = "Français", Value = "fr-CA" });
    langues.Add(new SelectListItem() { Text = "English", Value = "en-US" });
    langues.Add(new SelectListItem() { Text = "Español", Value = "es-US" });
    langues.Add(new SelectListItem() { Text = "Português", Value = "pt-BR" });
}

<div class="navbar navbar-inverse navbar-fixed-top">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            @Html.ActionLink("Prog Web II", "Index", null, new { @class = "navbar-brand" })
        </div>
        <div class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
                @if (User.Identity.IsAuthenticated)
                {
                    <li>@Html.ActionLink(User.Identity.Name, "Profil", "Utilisateurs")  @*<text>&nbsp; &nbsp;</text>*@</li> 
                    <li>@Html.ActionLink(StringShared.Deconnexion, "Deconnexion", "Utilisateurs")</li>
                    <li>                        
                        @*http://stackoverflow.com/questions/23889443/mvc-4-calling-action-method-on-dropdown-list-select-change*@
                        @using (Html.BeginForm("ChangerLangue", "Home", FormMethod.Post))
                        {
                            //http://stackoverflow.com/questions/7231157/how-to-submit-form-on-change-of-dropdown-list
                            @Html.DropDownList("langue", langues, new { @class = "form-control", @onchange = "this.form.submit()" })
                        }
                    </li>
                }
                else
                {
                    <li>@Html.ActionLink(StringShared.Inscription, "Inscription", "Utilisateurs")   @*<text>&nbsp; &nbsp;</text>*@</li> 
                    <li>@Html.ActionLink(StringShared.Connexion, "Connexion", "Utilisateurs")</li>
                    
                    <li>
                        @using (Html.BeginForm("ChangerLangue", "Home", FormMethod.Post))
                        {
                            @Html.DropDownList("langue", langues, new { @class = "form-control", @onchange = "this.form.submit()" })
                        }
                    </li>                       
                }
            </ul>
        </div>
    </div>
</div>

Wiki/Views/Shared/_Layout.cshtml
@{
//IList<string> titres = ViewBag.titres;
}

<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Prog Web II @ViewBag.Title</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    @Html.Partial("Menu")
    <div class="container">
        <div class="row content">
            <br /><br />
            <div class="col-sm-3 sidenav">
                @*@RenderSection("gauche", required: false)*@
                <div class="well">
                    @Html.Action("ActualiserTitres", "Base")
                </div>
            </div>
            <div class="col-sm-9">
                @RenderBody()
            </div>
        </div>
        <footer class="container-fluid">
            <p>&copy; @DateTime.Now.Year - Mon Wiki</p>
        </footer>
    </div>
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
</body>
</html>